### ISSUE TITLE
I have two problem!

### ISSUE THREAD

**Issue by pavlosts** [Jacajack/cmorse#1]
Hello! I am trying to implement the greek alphabet but I have two problems.

1) For some reason I can't print anything more than what was already there.

2) I added a new flag to specify the language of the given text but it is not working properly.

Any help? Thank you!

**Comment by Jacajack** [comment]
Hi, @pavlosts !
I'm really, really glad to see someone contribute finally! :smile:

Unfortunately, I can't help you right now, because I'm away from home.

I can suggest changing `morse` array type from `char` to `wchar_t`,
because I think there are no Greek characters in standard ASCII character
set. I can do that when I'm back (today evening).

Also, I'll take a deeper look at your code then.

Cheers
~Jacajack

**Comment by Jacajack** [comment]
@pavlosts - your code probably doesn't work because of this line:

``` c
if(strcmp(lang, "en") && (j <= 25 || j > 49) )
```

It looks like you missed `!` before`strcmp`. In this case it should look like this:

``` c
if( !strcmp(lang, "en") && (j <= 25 || j > 49) )
```

I'm going to create branch for developing support for more languages today. I plan to add new parsing arrays for few alphabets (someday in future). Managing multiple arrays should be much easier, than selective reading from one, longer. I'd be really happy if You could help me to implement Greek there. Stay tuned for repo updates, so you don't waste your time, please :)

**Comment by pavlosts** [comment]
1. Thanks for mentioning the `!`. I completely forgot it.
2. I tried changing `char` with `wchar_t` and a river of errors flew through my terminal.
3. My biggest problem so far is the message 

> cmorse: unknown option: -l

It's my first time working with flags and I don't know how to fix it. Thanks for helping! :)

**Comment by Jacajack** [comment]
@pavlosts, Remember that if you change `char` to `wchar_t`, you have to change whole bunch of functions (like `strlen`) to their wide character alternative. I'm going to do that today for you, also I can implement language flags.

By the way, I can't see any obvious reason why you get the error. Are you sure, than you are working on the same version as your fork?

**Comment by pavlosts** [comment]
I am not home right now, so I can't check but I think so. I'll wait for your changes first and then see what I can do.

**Comment by Jacajack** [comment]
@pavlosts, that's alright. ~~At this moment I almost finished changing everything to `wchar_t`.~~ 
I finished and this is basically how my version of character sets works. I might commit some little changes, but don't worry about that.
I guess everything should be self explanatory.
Though, if you have any questions, we can discuss them on IRC, let's say. (`freenode, #cmorse` - I guess that room doesn't exist yet, so it should be fine)

**Comment by Jacajack** [comment]
@pavlosts, I can see we missed each other on IRC. Sorry, I didn't notice anything.
Maybe, when you are online again, write something here, so I get an email, and know to join you. :stuck_out_tongue_closed_eyes:
